In [10]:
import numpy as np
import pandas as pd

In [11]:
df=pd.read_csv(r"D:\SEM-5\ML-LAB\ex-1\new_forest_full_dataset.csv")
df

,day,month,year,Region,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,1,6,2012,Bejaia,29,57,18,0.0,65.7,3.4,7.6,1.3,3.4,0.5,no
1,2,6,2012,Bejaia,29,61,13,1.3,64.4,4.1,7.6,1.0,3.9,0.4,no
2,3,6,2012,Bejaia,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,no
3,4,6,2012,Bejaia,25,89,13,2.5,28.6,1.3,6.9,0.0,1.7,0.0,no
4,5,6,2012,Bejaia,27,77,16,0.0,64.8,3.0,14.2,1.2,3.9,0.5,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,26,9,2012,Sidi-Bel-Abbes,30,65,14,0.0,85.4,16.0,44.5,4.5,16.9,6.5,yes
240,27,9,2012,Sidi-Bel-Abbes,28,87,15,4.4,41.1,6.5,8.0,0.1,6.2,0.0,no
241,28,9,2012,Sidi-Bel-Abbes,27,87,29,0.5,45.9,3.5,7.9,0.4,3.4,0.2,no
242,29,9,2012,Sidi-Bel-Abbes,24,54,18,0.1,79.7,4.3,15.2,1.7,5.1,0.7,no
243,30,9,2012,Sidi-Bel-Abbes,24,64,15,0.2,67.3,3.8,16.5,1.2,4.8,0.5,no

In [12]:
df.columns=df.columns.str.strip()
df['Classes']=df['Classes'].str.strip()
df['Classes'].value_counts()

Classes
yes    138
no     106
Name: count, dtype: int64

In [13]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Classes']=le.fit_transform(df['Classes'])
df

,day,month,year,Region,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,1,6,2012,Bejaia,29,57,18,0.0,65.7,3.4,7.6,1.3,3.4,0.5,0
1,2,6,2012,Bejaia,29,61,13,1.3,64.4,4.1,7.6,1.0,3.9,0.4,0
2,3,6,2012,Bejaia,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,0
3,4,6,2012,Bejaia,25,89,13,2.5,28.6,1.3,6.9,0.0,1.7,0.0,0
4,5,6,2012,Bejaia,27,77,16,0.0,64.8,3.0,14.2,1.2,3.9,0.5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,26,9,2012,Sidi-Bel-Abbes,30,65,14,0.0,85.4,16.0,44.5,4.5,16.9,6.5,1
240,27,9,2012,Sidi-Bel-Abbes,28,87,15,4.4,41.1,6.5,8.0,0.1,6.2,0.0,0
241,28,9,2012,Sidi-Bel-Abbes,27,87,29,0.5,45.9,3.5,7.9,0.4,3.4,0.2,0
242,29,9,2012,Sidi-Bel-Abbes,24,54,18,0.1,79.7,4.3,15.2,1.7,5.1,0.7,0
243,30,9,2012,Sidi-Bel-Abbes,24,64,15,0.2,67.3,3.8,16.5,1.2,4.8,0.5,0

In [14]:
df=df.drop('Region',axis=1)

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,1,6,2012,29,57,18,0.0,65.7,3.4,7.6,1.3,3.4,0.5,0
1,2,6,2012,29,61,13,1.3,64.4,4.1,7.6,1.0,3.9,0.4,0
2,3,6,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,0
3,4,6,2012,25,89,13,2.5,28.6,1.3,6.9,0.0,1.7,0.0,0
4,5,6,2012,27,77,16,0.0,64.8,3.0,14.2,1.2,3.9,0.5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,26,9,2012,30,65,14,0.0,85.4,16.0,44.5,4.5,16.9,6.5,1
240,27,9,2012,28,87,15,4.4,41.1,6.5,8.0,0.1,6.2,0.0,0
241,28,9,2012,27,87,29,0.5,45.9,3.5,7.9,0.4,3.4,0.2,0
242,29,9,2012,24,54,18,0.1,79.7,4.3,15.2,1.7,5.1,0.7,0
243,30,9,2012,24,64,15,0.2,67.3,3.8,16.5,1.2,4.8,0.5,0

In [15]:
df=df.drop('year',axis=1)

In [16]:
df

,day,month,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,1,6,29,57,18,0.0,65.7,3.4,7.6,1.3,3.4,0.5,0
1,2,6,29,61,13,1.3,64.4,4.1,7.6,1.0,3.9,0.4,0
2,3,6,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,0
3,4,6,25,89,13,2.5,28.6,1.3,6.9,0.0,1.7,0.0,0
4,5,6,27,77,16,0.0,64.8,3.0,14.2,1.2,3.9,0.5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,26,9,30,65,14,0.0,85.4,16.0,44.5,4.5,16.9,6.5,1
240,27,9,28,87,15,4.4,41.1,6.5,8.0,0.1,6.2,0.0,0
241,28,9,27,87,29,0.5,45.9,3.5,7.9,0.4,3.4,0.2,0
242,29,9,24,54,18,0.1,79.7,4.3,15.2,1.7,5.1,0.7,0
243,30,9,24,64,15,0.2,67.3,3.8,16.5,1.2,4.8,0.5,0

In [17]:

def activation(net_inp,ch):
    if(ch==1):
        return net_inp
    elif(ch==2):
        return round(1/(1+np.exp(-net_inp)))
    elif(ch==3):
        return round((1-np.exp(-net_inp))/(1+np.exp(-net_inp)))

def predict(inputs,weights,bias,ch):
    inputs=np.dot(inputs,weights)+bias
    return activation(inputs,ch)

def feed_forward(data,target,weights,bias,lr,ch):
    converged=False
    epoch=0
    print("\len ",len(data))
    while not converged and epoch<=10:
        converged=True
        print("EPOCH : ",epoch)
        print("Weights : ",weights)
        print("Bias :",bias)
        print(data[0])
        for i in range(len(data)):
            pred=predict(data[i],weights,bias,ch)
            error=target[i]-pred
            #print("for data ",data[i],"PRED is ",pred)
            if error!=0:
             #  print("Updating Weights : ")
                weights+=lr*error*data[i]
                bias+=lr*error
              # print("New Weights : ",weights)
               #print("New Bias :",bias)
                converged=False
        epoch+=1
   # print('\nFinal weights:',weights)
    #print('Bias:',bias,"\n")
    return weights,bias

In [19]:
X=np.array(df.iloc[:,:-1])
y=np.array(df['Classes'])

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
X_train.shape

(195, 12)

In [21]:
weights=np.random.randn(len(df.columns[:-1]))
print(weights)
weights.shape

[ 0.67857701 -0.41673601 -2.35132921  1.44988076 -2.25807493 -1.25077753
  0.09647674 -1.01136999  0.12458759  0.8623122   1.11353525  1.3745716 ]

(12,)

In [22]:
bias=float(input("Enter the bias:"))
lr=float(input("Enter the learning rate:"))
ch=int(input("1.IDENTITY FXN\n2.BINARY SIGMOIDAL\n3.BIPOLAR SIGMOIDAL\nEnter the Choice of A.F : "))
if(ch==2 or ch==3):
    thresh=float(input('Enter the threshold:'))

weights,bias=feed_forward(X_train,y_train,weights,bias,lr,ch)
print("\nFinal Weights and Bias : ",weights,bias)

pred=[]
for test in X_test:
    p=predict(test,weights,bias,ch)
    pred.append(p)
    print("Input:",test,"Prediction:",p)
print(pred)

Enter the bias:0
Enter the learning rate:1
1.IDENTITY FXN
2.BINARY SIGMOIDAL
3.BIPOLAR SIGMOIDAL
Enter the Choice of A.F : 2
Enter the threshold:0.5
\len  195
EPOCH :  0
Weights :  [ 0.67857701 -0.41673601 -2.35132921  1.44988076 -2.25807493 -1.25077753
  0.09647674 -1.01136999  0.12458759  0.8623122   1.11353525  1.3745716 ]
Bias : 0.0
[26.   6.  31.  64.  18.   0.  86.8 17.8 71.8  6.7 21.6 10.6]
EPOCH :  1
Weights :  [-150.32142299  -24.41673601  -80.35132921 -240.55011924  -34.25807493
  -12.55077753  104.89647674   59.98863001  171.02458759  111.5623122
   83.51353525  149.4745716 ]
Bias : -3.0
[26.   6.  31.  64.  18.   0.  86.8 17.8 71.8  6.7 21.6 10.6]
EPOCH :  2
Weights :  [-215.32142299  -29.41673601  -85.35132921 -239.55011924  -68.25807493
  -28.45077753  215.99647674   82.38863001  152.42458759  164.1623122
  113.31353525  225.1745716 ]
Bias : -4.0
[26.   6.  31.  64.  18.   0.  86.8 17.8 71.8  6.7 21.6 10.6]
EPOCH :  3
Weights :  [-326.32142299  -44.41673601 -119.35132921 -225.55011924 -105.25807493
  -49.55077753  246.79647674   68.68863001   49.82458759  214.3623122
  105.41353525  296.1745716 ]
Bias : -6.0
[26.   6.  31.  64.  18.   0.  86.8 17.8 71.8  6.7 21.6 10.6]
EPOCH :  4
Weights :  [-355.32142299  -60.41673601 -164.35132921 -228.55011924 -140.25807493
  -74.25077753  275.79647674   88.88863001   43.12458759  264.5623122
  132.51353525  371.7745716 ]
Bias : -8.0
[26.   6.  31.  64.  18.   0.  86.8 17.8 71.8  6.7 21.6 10.6]
EPOCH :  5
Weights :  [-335.32142299  -78.41673601 -217.35132921 -236.55011924 -157.25807493
  -91.25077753  269.39647674  113.38863001   64.92458759  309.0623122
  166.51353525  443.5745716 ]
Bias : -10.0
[26.   6.  31.  64.  18.   0.  86.8 17.8 71.8  6.7 21.6 10.6]
EPOCH :  6
Weights :  [-411.32142299  -83.41673601 -240.35132921 -188.55011924 -188.25807493
 -100.75077753  287.49647674   95.98863001   19.22458759  334.7623122
  160.01353525  478.9745716 ]
Bias : -11.0
[26.   6.  31.  64.  18.   0.  86.8 17.8 71.8  6.7 21.6 10.6]
EPOCH :  7
Weights :  [-413.32142299  -84.41673601 -280.35132921 -150.55011924 -198.25807493
 -108.55077753  286.39647674   98.18863001   34.42458759  358.5623122
  176.01353525  516.5745716 ]
Bias : -12.0
[26.   6.  31.  64.  18.   0.  86.8 17.8 71.8  6.7 21.6 10.6]
EPOCH :  8
Weights :  [-389.32142299  -95.41673601 -328.35132921 -230.55011924 -227.25807493
 -108.25077753  292.19647674  129.28863001   66.62458759  398.0623122
  218.61353525  581.0745716 ]
Bias : -14.0
[26.   6.  31.  64.  18.   0.  86.8 17.8 71.8  6.7 21.6 10.6]
EPOCH :  9
Weights :  [-421.32142299 -100.41673601 -360.35132921 -190.55011924 -245.25807493
 -117.25077753  311.49647674  110.28863001   30.42458759  427.4623122
  213.91353525  624.3745716 ]
Bias : -15.0
[26.   6.  31.  64.  18.   0.  86.8 17.8 71.8  6.7 21.6 10.6]
EPOCH :  10
Weights :  [-451.32142299 -109.41673601 -390.35132921 -186.55011924 -252.25807493
 -124.35077753  315.09647674  113.88863001   19.32458759  450.1623122
  231.11353525  660.8745716 ]
Bias : -16.0
[26.   6.  31.  64.  18.   0.  86.8 17.8 71.8  6.7 21.6 10.6]

Final Weights and Bias :  [-463.32142299 -115.41673601 -410.35132921 -177.55011924 -275.25807493
 -129.25077753  325.29647674  117.08863001    7.72458759  470.9623122
  246.11353525  693.6745716 ] -17.0
Input: [17.   8.  42.  24.   9.   0.  96.  30.3 76.4 15.7 30.4 24. ] Prediction: 1
Input: [ 9.   6.  27.  59.  18.   0.1 78.1  8.5 14.7  2.4  8.3  1.9] Prediction: 0
Input: [14.   7.  34.  61.  13.   0.6 73.9  7.8 22.9  1.4  8.4  0.8] Prediction: 0
Input: [ 20.    8.   35.   68.   19.    0.   88.3  25.9 130.6   8.8  34.7  16.8] Prediction: 1
Input: [15.   7.  34.  45.  17.   0.  90.5 18.  24.1 10.9 17.7 14.1] Prediction: 1
Input: [ 6.   6.  35.  54.  11.   0.1 83.7  8.4 26.3  3.1  9.3  3.1] Prediction: 1
Input: [ 1.   8.  36.  45.  14.   0.  78.8  4.8 10.2  2.   4.7  0.9] Prediction: 1
Input: [12.   8.  39.  21.  17.   0.4 93.  18.4 41.5 15.5 18.4 18.8] Prediction: 1
Input: [15.   8.  35.  46.  13.   0.3 83.9 16.9 54.2  3.5 19.   5.5] Prediction: 1
Input: [30.   9.  24.  64.  15.   0.2 67.3  3.8 16.5  1.2  4.8  0.5] Prediction: 0
Input: [ 21.    8.   36.   58.   19.    0.   88.6  29.6 141.1   9.2  38.8  18.4] Prediction: 1
Input: [ 9.   8.  35.  59.  17.   0.  87.4 14.8 57.   6.9 17.9  9.9] Prediction: 1
Input: [ 2.   9.  28.  67.  19.   0.  75.4  2.9 16.3  2.   4.   0.8] Prediction: 0
Input: [23.   6.  32.  62.  18.   0.1 81.4  8.2 47.7  3.3 11.5  3.8] Prediction: 0
Input: [ 6.   8.  30.  54.  14.   3.1 70.5 11.   9.1  1.3 10.5  0.8] Prediction: 0
Input: [21.   6.  30.  78.  14.   0.  81.   6.3 31.6  2.6  8.4  2.2] Prediction: 0
Input: [ 19.    8.   35.   62.   19.    0.   89.4  23.2 120.9   9.7  31.3  17.2] Prediction: 1
Input: [ 5.   9.  30.  58.  12.   4.1 66.1  4.   8.4  1.   3.9  0.4] Prediction: 0
Input: [14.   9.  22.  76.  26.   8.3 47.4  1.1  7.   0.4  1.6  0.1] Prediction: 0
Input: [ 30.    8.   35.   70.   17.    0.8  72.7  25.2 180.4   1.7  37.4   4.2] Prediction: 0
Input: [ 8.   9.  30.  88.  14.   0.  82.5  6.6 26.1  3.   8.1  2.7] Prediction: 0
Input: [ 3.   6.  26.  82.  22.  13.1 47.1  2.5  7.1  0.3  2.7  0.1] Prediction: 0
Input: [28.   6.  37.  37.  13.   0.  92.5 27.2 52.4 11.7 27.1 18.4] Prediction: 1
Input: [ 2.   6.  30.  73.  13.   4.  55.7  2.7  7.8  0.6  2.9  0.2] Prediction: 0
Input: [ 4.   7.  34.  58.  18.   0.  88.  13.6 36.8  8.  14.1  9.9] Prediction: 1
Input: [ 4.   9.  30.  66.  15.   0.2 73.5  4.1 26.6  1.5  6.   0.7] Prediction: 0
Input: [ 8.   8.  37.  56.  11.   0.  87.4 11.2 20.2  5.2 11.   5.9] Prediction: 1
Input: [10.   7.  33.  69.  13.   0.7 66.6  6.   9.3  1.1  5.8  0.5] Prediction: 0
Input: [11.   6.  31.  65.  14.   0.  84.5 12.5 54.3  4.  15.8  5.6] Prediction: 1
Input: [ 8.   6.  30.  73.  15.   0.  86.6 12.1 38.3  5.6 13.5  7.1] Prediction: 1
Input: [ 27.    7.   36.   48.   13.    0.   90.3  22.2 108.5   8.7  29.4  15.3] Prediction: 1
Input: [25.   9.  26.  81.  21.   5.8 48.6  3.   7.7  0.4  3.   0.1] Prediction: 0
Input: [20.   6.  30.  80.  16.   0.4 59.8  3.4 27.1  0.9  5.1  0.4] Prediction: 0
Input: [17.   9.  31.  52.  14.   0.  87.7  6.4 24.3  6.2  7.7  5.9] Prediction: 1
Input: [15.   8.  36.  55.  13.   0.3 82.4 15.6 92.5  3.7 22.   6.3] Prediction: 1
Input: [16.   6.  29.  89.  13.   0.7 36.1  1.7  7.6  0.   2.2  0. ] Prediction: 0
Input: [19.   8.  35.  66.  15.   0.1 82.7 32.7 96.8  3.3 35.5  7.7] Prediction: 1
Input: [31.   8.  28.  80.  21.  16.8 52.5  8.7  8.7  0.6  8.3  0.3] Prediction: 0
Input: [12.   7.  31.  75.  13.   0.1 75.1  7.9 27.7  1.5  9.2  0.9] Prediction: 0
Input: [17.   7.  32.  81.  17.   0.  84.6 21.1 42.3  4.7 20.9  7.7] Prediction: 1
Input: [ 7.   6.  33.  54.  13.   0.  88.2  9.9 30.5  6.4 10.9  7.2] Prediction: 1
Input: [ 29.    7.   32.   73.   15.    0.   86.6  26.7 127.    5.6  35.   11.9] Prediction: 1
Input: [25.   7.  39.  64.   9.   1.2 73.8 11.7 15.9  1.1 11.4  0.7] Prediction: 0
Input: [ 2.   8.  35.  55.  12.   0.4 78.   5.8 10.   1.7  5.5  0.8] Prediction: 0
Input: [12.   6.  26.  81.  19.   0.  84.  13.8 61.4  4.8 17.7  7.1] Prediction: 1
Input: [ 2.   9.  22.  86.  15.  10.1 30.5  0.7  7.   0.   1.1  0. ] Prediction: 0
Input: [21.   6.  32.  55.  14.   0.  86.2  8.3 18.4  5.   8.2  4.9] Prediction: 0
Input: [24.   7.  28.  78.  16.   0.1 70.   9.6 79.7  1.4 14.7  1.3] Prediction: 0
Input: [ 17.    8.   37.   52.   18.    0.   89.3  16.  100.7   9.7  22.9  14.6] Prediction: 1
[1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1]

C:\Users\MAAL SUBIKSHA\AppData\Local\Temp\ipykernel_11912\3062213435.py:5: RuntimeWarning: overflow encountered in exp
  return round(1/(1+np.exp(-net_inp)))

In [23]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,pred))

0.8979591836734694